### ISSUE TITLE
Keypad is not a constructor using example code

### ISSUE THREAD

**Issue by Ru-Pirie** [AlexKutschera/rpi-keypad#4]
When using the default code example an error is thrown when defining input,
```
var input = new Keypad(
            ^
TypeError: Keypad is not a constructor
    at Object.<anonymous> (/home/pi/Documents/I2C/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**Comment by AlexKutschera** [comment]
could you provide the code how you import the library as it's usally an error when importing from the wrong namespace.
For example in Typescript 
`import Keypad from "rpi-keypad"` (correct) vs `import {Keypad} from "rpi-keypad"`
or in Javascript 
`var Keypad = require("rpi-keypad")` (correct) vs `var {Keypad} = require("rpi-keypad")` or `var Keypad = require("rpi-keypad").Keypad`

**Comment by Ru-Pirie** [comment]
Fixed on own

**Comment by AlexKutschera** [comment]
Could you provide your solution in case other users have the same issue?

**Comment by Dimitryum** [comment]
Hi,

actually, when using the default code example, console show me the same error above.

My import library code is: 

var Keypad = require("rpi-keypad"):

and the error is:

TypeError: Keypad is not a constructor([

**Comment by Ru-Pirie** [comment]
> Could you provide your solution in case other users have the same issue?

So sorry I have long since moved on from this project, I can't remember.

**Comment by Ru-Pirie** [comment]
I'm going to delve back into this and see if i can work it out!

**Comment by Ru-Pirie** [comment]
On inspection the module itself seems to be ok there does need to be some tweaking to the example code (pull request made) still failing on the Raspi for some reason.

Corrected code:
```js
const Keypad = require("rpi-keypad");

const input = new Keypad.default(
    [
        ["1", "2", "3", "A"],
        ["4", "5", "6", "B"],
        ["7", "8", "9", "C"],
        ["*", "0", "#", "D"],
    ],                  // keypad layout
    [40, 38, 36, 32],   // row GPIO pins
    [37, 35, 33, 31],   // colum GPIO pins
    // additional:
    true,               // use key press events
    100                 // interval in ms to poll for key events
);
    
// using own polling
setInterval(() => {
    const key = input.getKey();
    if (key != null){
        console.log("key pressed: " + key);
    } else {
        console.log("no key pressed");
    }
}, 100);

// using events
input.on("keypress", (key) => {
    console.log("key pressed: " + key);
})
```

**Comment by Ru-Pirie** [comment]
Ok fully fixed, use the code above and when running on the pi make sure to run the index.js file as a sudo user. 

`sudo node index.js` :)
